baseURL = "https://rocstar.wobbly.earth/"
languageCode = "en-us"
title = "ROCSTAR"
theme = "ananke"
publishDir = "docs"

[params]
  body_classes = "noto bg-near-white"
  custom_css = ["css/rocstar.css"]
  background_color_class= "bg-near-black"
  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/r_rietje"
  mail = "mailto:yakhontova@geod.uni-bonn.de"
  instagram = ""
  youtube = ""
  github = "https://github.com/orgs/wobbly-earth/teams"
  gitlab = ""
  linkedin = ""
  mastodon = ""
[[resources]]
  name = "sandysteps"
  src = "resources/images/sandysteps_orig.jpg"
